"use client";
import { FormEvent, useState } from "react";
import type { Product } from "@/lib/products";
import type { SiteContent } from "@/lib/default-content";

export function QuoteForm({ initialProduct = "", products, copy, email }: { initialProduct?: string; products: Product[]; copy: SiteContent["form"]; email: string }) {
  const [prepared, setPrepared] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const subject = encodeURIComponent(`${copy.emailSubjectPrefix} — ${String(f.get("product"))}`); const body = encodeURIComponent(`Name: ${f.get("name")}\nCompany: ${f.get("company")}\nCountry: ${f.get("country")}\nProduct: ${f.get("product")}\nQuantity: ${f.get("quantity")}\nDestination port: ${f.get("destination")}\nIncoterm: ${f.get("incoterm")}\n\nMessage:\n${f.get("message")}`); setPrepared(true); window.location.href = `mailto:${email}?subject=${subject}&body=${body}`; }
  return <form className="quote-form" onSubmit={submit}><div className="form-heading"><div><span>{copy.buyerStep}</span><div><p>{copy.buyerKicker}</p><h2>{copy.buyerTitle}</h2></div></div><small>{copy.requiredNote}</small></div><div className="form-grid buyer-grid"><label><span>{copy.nameLabel}</span><input name="name" required placeholder={copy.namePlaceholder} /></label><label><span>{copy.companyLabel}</span><input name="company" required placeholder={copy.companyPlaceholder} /></label><label className="field-wide"><span>{copy.countryLabel}</span><input name="country" required placeholder={copy.countryPlaceholder} /></label></div><div className="form-heading form-heading-secondary"><div><span>{copy.shipmentStep}</span><div><p>{copy.shipmentKicker}</p><h2>{copy.shipmentTitle}</h2></div></div></div><div className="form-grid shipment-grid"><label><span>{copy.productLabel}</span><select name="product" required defaultValue={initialProduct}><option value="" disabled>{copy.productPlaceholder}</option>{products.map((p) => <option key={p.slug}>{p.name}</option>)}<option>{copy.mixedContainer}</option></select></label><label><span>{copy.quantityLabel}</span><input name="quantity" placeholder={copy.quantityPlaceholder} /></label><label><span>{copy.destinationLabel}</span><input name="destination" placeholder={copy.destinationPlaceholder} /></label><label><span>{copy.incotermLabel}</span><select name="incoterm" defaultValue={copy.incotermOptions[0]}>{copy.incotermOptions.map((option) => <option key={option}>{option}</option>)}</select></label></div><label className="message-field field-wide"><span>{copy.messageLabel}</span><textarea name="message" rows={5} placeholder={copy.messagePlaceholder} /></label><div className="form-action"><div><span className="form-status-dot" /><p>{prepared ? copy.preparedNote : copy.privacyNote}</p></div><button className="button button-dark" type="submit">{copy.submitButton} <span>↗</span></button></div></form>;
}
