import Link from "next/link";
import { getCmsProducts, getSiteContent } from "@/lib/cms";
import { SiteShell } from "./components/SiteShell";
import { ProductVisual } from "./components/ProductVisual";
export const dynamic = "force-dynamic";

export default async function Home() {
  const [content, products] = await Promise.all([getSiteContent(), getCmsProducts()]); const c = content.home;
  return <SiteShell><section className="home-hero"><div className="hero-image" role="img" style={{ backgroundImage: `url(${c.heroImage})` }}><div className="hero-image-label"><span>{c.heroCoordinateOne}</span><span>{c.heroCoordinateTwo}</span></div></div><div className="hero-content page-shell"><div className="hero-copy"><p className="eyebrow light">{c.heroEyebrow}</p><h1>{c.heroTitle}<br /><em>{c.heroAccent}</em></h1></div><div className="hero-aside"><p>{c.heroDescription}</p><div className="hero-actions"><Link className="button button-cream" href="/products">{c.heroPrimaryButton} <span>↗</span></Link><Link className="text-link light" href="/about">{c.heroSecondaryButton} <span>→</span></Link></div></div></div><div className="hero-index">01</div></section>
  <section className="trust-line page-shell"><p>{c.trustIntro}</p><div>{c.trustItems.map((item) => <span key={item}>{item}</span>)}</div></section>
  <section className="featured page-shell"><div className="section-heading"><div><p className="eyebrow">{c.selectionEyebrow}</p><h2>{c.selectionTitle}<br /><em>{c.selectionAccent}</em></h2></div><div className="section-heading-note"><span>{c.selectionNote}</span><Link className="text-link" href="/products">{c.selectionButton} <span>→</span></Link></div></div><div className="featured-grid">{products.slice(0,3).map((p,i) => <article className="featured-card" key={p.slug}><Link href={`/products/${p.slug}`}><ProductVisual className={p.visualClass} label={p.name} image={p.image} /><div className="featured-meta"><span>0{i+1}</span><span>{p.category}</span></div><h3>{p.shortName}</h3><p>{p.description}</p><span className="text-link">{c.productButton} <b>↗</b></span></Link></article>)}</div></section>
  <section className="origin-story"><div className="origin-photo" role="img" style={{ backgroundImage: `url(${c.originImage})` }} /><div className="origin-copy"><p className="eyebrow light">{c.originEyebrow}</p><h2>{c.originTitle}<br /><em>{c.originAccent}</em></h2><p>{c.originDescription}</p><div className="stat-row">{c.originStats.map((s) => <div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div><Link className="button button-outline-light" href="/quality">{c.originButton} <span>↗</span></Link></div></section>
  <section className="process page-shell"><div className="section-heading"><div><p className="eyebrow">{c.processEyebrow}</p><h2>{c.processTitle}<br /><em>{c.processAccent}</em></h2></div><p className="process-intro">{c.processIntro}</p></div><div className="process-grid">{c.processSteps.map((step,i) => <article key={i}><span>{String(i+1).padStart(2,"0")}</span><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></section>
  <section className="trade-banner"><div className="trade-photo" role="img" style={{ backgroundImage: `url(${c.tradeImage})` }} /><div className="trade-card"><p className="eyebrow light">{c.tradeEyebrow}</p><h2>{c.tradeTitle}</h2><ul>{c.tradeItems.map((item,i) => <li key={i}><span>{String(i+1).padStart(2,"0")}</span>{item}</li>)}</ul><Link className="text-link light" href="/contact">{c.tradeButton} <span>→</span></Link></div></section></SiteShell>;
}
