export const defaultSiteContent = {
  settings: {
    brandName: "RKEXPO",
    brandSubtitle: "DEHYDRATED EXPORTS",
    tradeStripLeft: "Indian origin · Global standards",
    tradeStripRight: "Export documentation · FOB / CIF",
    navHome: "Home",
    navProducts: "Products",
    navAbout: "Our story",
    navQuality: "Quality",
    navContact: "Contact",
    headerCta: "Request a quote",
    email: "exports@rkexpo.com",
    phone: "+91 98765 43210",
    phoneLink: "+919876543210",
    address: "Rajkot, Gujarat, India",
    hours: "Mon–Sat · 09:00–18:00 IST",
    ports: "FOB Mundra / Nhava Sheva",
    footerEyebrow: "Start a conversation",
    footerTitle: "Let’s move good ingredients",
    footerTitleAccent: "across borders.",
    footerCopy: "Indian dehydrated ingredients, prepared for modern international food supply chains.",
    footerExploreLabel: "Explore",
    footerContactLabel: "Contact",
    footerTradeLabel: "Trade desk",
    copyright: "© 2026 RKExpo",
    footerNote: "Demo catalogue · Specifications subject to contract",
    seoTitle: "RKExpo | Dehydrated Ingredients from India",
    seoDescription: "Indian dehydrated onion, garlic, and selected vegetable powders prepared for international buyers.",
    socialTitle: "Indian ingredients. Ready for the world.",
    socialDescription: "Export-ready dehydrated onion, garlic, and vegetable powders from India.",
    socialImage: "/og-cms.png",
  },
  home: {
    heroEyebrow: "Dehydrated ingredients from India",
    heroTitle: "Rooted in India.",
    heroAccent: "Ready for the world.",
    heroDescription: "We supply dehydrated onion, garlic, and selected vegetable powders to food manufacturers and ingredient buyers worldwide.",
    heroPrimaryButton: "Explore products",
    heroSecondaryButton: "Discover our story",
    heroImage: "https://d3fwccq2bzlel7.cloudfront.net/Pictures/1024x536/6/9/8/145698_genonionsgarlicadobestock_216623468_611402.jpeg",
    heroCoordinateOne: "21.17° N",
    heroCoordinateTwo: "72.83° E",
    trustIntro: "From selected produce to export-ready ingredients",
    trustItems: ["Origin-led sourcing", "Controlled dehydration", "Flexible formats", "Global shipping"],
    selectionEyebrow: "Our selection",
    selectionTitle: "Ingredients with a clear",
    selectionAccent: "point of origin.",
    selectionNote: "08 export-ready products",
    selectionButton: "View full catalogue",
    productButton: "Explore product",
    originImage: "https://www.asz.cz/res/archive/390/058126.jpg?seek=1671692214",
    originEyebrow: "Why RKExpo",
    originTitle: "Closer to origin.",
    originAccent: "Stronger at destination.",
    originDescription: "We coordinate produce sourcing, dehydration, grading, packing, testing, and export documentation through one accountable trade desk.",
    originStats: [
      { value: "03", label: "Product families" },
      { value: "08", label: "Catalogue products" },
      { value: "20/40", label: "Ft container options" },
    ],
    originButton: "See our process",
    processEyebrow: "How we work",
    processTitle: "One chain.",
    processAccent: "Every detail covered.",
    processIntro: "Clear milestones from your required ingredient format to final shipping documents.",
    processSteps: [
      { title: "Source", copy: "Produce-region selection and supplier verification." },
      { title: "Dehydrate", copy: "Controlled processing to the required ingredient form." },
      { title: "Grade", copy: "Cut-size grading, testing, and export packing." },
      { title: "Ship", copy: "Documentation and freight coordination to port." },
    ],
    tradeImage: "https://images.unsplash.com/photo-1774929103406-59c8882a9954?auto=format&fit=crop&q=82&w=1900",
    tradeEyebrow: "Trade-ready support",
    tradeTitle: "Built for the practical side of global buying.",
    tradeItems: ["Pre-shipment samples", "Third-party inspection support", "Phytosanitary & origin documents", "Private-label packaging"],
    tradeButton: "Talk to the export desk",
  },
  productsPage: {
    heroNumber: "02",
    heroKicker: "Product catalogue",
    heroTitle: "Indian ingredients.",
    heroAccent: "Prepared to specification.",
    heroIntro: "Explore our dehydrated onion, garlic, and powder range. Format, packing, testing, and documentation can be aligned to your destination market.",
    allFilterLabel: "All",
    productCountSuffix: "products",
    cardButton: "View product details",
    noteKicker: "Need a product not listed?",
    noteTitle: "Tell us the format, quantity, and destination. Our sourcing desk will check availability.",
    noteButton: "Send a requirement",
    breadcrumbLabel: "Catalogue",
    originLabel: "Indian origin",
    availableFormatsLabel: "Available formats",
    availablePackingLabel: "Available packing",
    suitedForLabel: "Best suited for",
    requestButton: "Request this product",
    qualityButton: "View quality process",
    specificationNote: "Indicative product information. Final parameters are confirmed against contract and pre-shipment sample.",
    relatedEyebrow: "Continue browsing",
    relatedTitle: "More from the",
    relatedAccent: "catalogue.",
  },
  about: {
    heroNumber: "03",
    heroKicker: "Our story",
    heroTitle: "Trade should feel",
    heroAccent: "closer to the source.",
    heroIntro: "RKExpo was shaped around a simple idea: international buyers deserve clearer origin, steadier communication, and fewer hand-offs.",
    primaryImage: "https://www.asz.cz/res/archive/390/058126.jpg?seek=1671692214",
    primaryImageAlt: "Freshly harvested onions in a field",
    quote: "Good export relationships are built on what arrives—not only what was promised.",
    secondaryImage: "https://d3fwccq2bzlel7.cloudfront.net/Pictures/1024x536/6/9/8/145698_genonionsgarlicadobestock_216623468_611402.jpeg",
    secondaryImageAlt: "Selected onions and garlic",
    storyEyebrow: "From western India",
    storyTitle: "A hands-on trade desk for the entire journey.",
    storyParagraphs: [
      "Based in Gujarat, within reach of produce-growing regions and western ports, we coordinate suppliers, dehydration units, laboratories, packers, and freight partners around one confirmed requirement.",
      "Our role is practical: define the right ingredient format early, keep product and paperwork aligned, and make each shipment easier to follow from origin to destination port.",
    ],
    values: [
      { title: "Clarity over claims", copy: "We define measurable requirements and confirm them before shipment." },
      { title: "Origin matters", copy: "We select suppliers and processing partners for their fit with each ingredient." },
      { title: "Built for repeat trade", copy: "Consistency, communication, and practical problem-solving come first." },
    ],
    ctaText: "Looking for a dependable India sourcing partner?",
    ctaButton: "Meet the export desk",
  },
  quality: {
    heroNumber: "04",
    heroKicker: "Quality assurance",
    heroTitle: "Measured at origin.",
    heroAccent: "Verified at every gate.",
    heroIntro: "A visible control path connects raw-material intake, controlled dehydration, precision sorting, contaminant detection, and export packing.",
    heroImage: "https://d3fwccq2bzlel7.cloudfront.net/Pictures/1024x536/6/9/8/145698_genonionsgarlicadobestock_216623468_611402.jpeg",
    heroStat: "12",
    heroStatLabel: "defined stages from farm intake to the finished export pack",
    architectureEyebrow: "Quality architecture",
    architectureTitle: "Three layers of control.",
    architectureAccent: "One accountable lot.",
    principles: [
      { title: "Process control", copy: "Time, temperature, moisture, sanitation, and cut size are checked at the stages where they matter." },
      { title: "Product verification", copy: "Optical sorting, detector challenges, and manual inspection create successive quality gates." },
      { title: "Lot evidence", copy: "Batch identity, inspection records, packing checks, and shipment documents stay connected to the order." },
    ],
    journeyEyebrow: "Interactive process map",
    journeyTitle: "Follow one lot from",
    journeyAccent: "farm to final pack.",
    journeyIntro: "Select any stage to see the operating focus, control checks, and expected release point.",
    stageLabel: "Stage",
    releaseLabel: "Release point",
    checksLabel: "Control checks",
    stages: [
      { phase: "Source", title: "Farm intake", summary: "Fresh onions and other produce are received from approved supply partners and assigned to an identifiable lot.", checks: ["Visual condition inspection", "TSS measurement where applicable", "Foreign-material screening"], outcome: "Accepted raw-material lot" },
      { phase: "Prepare", title: "Wash & sanitise", summary: "Raw material moves through controlled washing and, where specified, an ozone-based sanitation stage.", checks: ["Water and sanitation control", "PPM verification", "Post-wash visual check"], outcome: "Clean product ready for cutting" },
      { phase: "Prepare", title: "Slice & feed", summary: "Prepared produce is cut to the contracted format and transferred evenly onto the processing belt.", checks: ["Cut-size verification", "Vernier calliper thickness check", "Belt-feed inspection"], outcome: "Consistent product geometry" },
      { phase: "Dehydrate", title: "Primary dehydration", summary: "A controlled multi-stage hot-air process removes the majority of moisture while protecting product character.", checks: ["Time and temperature log", "Airflow monitoring", "In-process moisture measurement"], outcome: "Evenly dehydrated product" },
      { phase: "Dehydrate", title: "Secondary drying", summary: "A finishing stage conditions the product toward the agreed final moisture requirement.", checks: ["Moisture verification", "Drying uniformity review", "Batch parameter record"], outcome: "Stable finished moisture" },
      { phase: "Stabilise", title: "Controlled cooling", summary: "Product travels on a food-grade conveyor into a controlled room or cold dryer before further handling.", checks: ["Room temperature monitoring", "Relative humidity monitoring", "Protected product transfer"], outcome: "Conditioned product for grading" },
      { phase: "Refine", title: "Size separation", summary: "Roller separation and aspiration classify slices, flakes, kibbled pieces, and lighter material.", checks: ["Requested size-band check", "Aspirator performance review", "Visible impurity inspection"], outcome: "Uniform product fraction" },
      { phase: "Refine", title: "Optical sorting", summary: "High-definition image sensing identifies roots, off-colour pieces, and other visible defects for removal.", checks: ["Sorter calibration", "Foreign-colour check", "Reject-stream review"], outcome: "Cleaner visual specification" },
      { phase: "Verify", title: "X-ray & metal detection", summary: "Product passes through detection controls designed to identify metallic and other specified dense contaminants.", checks: ["Detector challenge verification", "Critical-control-point record", "Corrective-action check"], outcome: "Verified control-point release" },
      { phase: "Verify", title: "Manual final sorting", summary: "A final human inspection removes remaining visible foreign bodies before the product reaches packing.", checks: ["Foreign-body inspection", "Colour and appearance review", "Line-clearance check"], outcome: "Packing-ready finished product" },
      { phase: "Pack", title: "Inner packing", summary: "Finished product is filled into moisture-resistant, food-grade inner liners selected for the shipment.", checks: ["Packing-material inspection", "Net-weight verification", "Seal integrity check"], outcome: "Protected primary pack" },
      { phase: "Pack", title: "Export packing", summary: "Inner packs are placed in paper sacks or corrugated boxes and marked to the customer’s requirements.", checks: ["Outer-pack inspection", "Label and lot-code check", "Final sealing and dispatch review"], outcome: "Export-ready consignment" },
    ],
    documentsEyebrow: "Document support",
    documentsTitle: "Paperwork that keeps the cargo moving.",
    documents: ["Certificate of origin", "Phytosanitary certificate", "Fumigation certificate", "Packing list & invoice", "Bill of lading", "Third-party inspection report"],
    certificationEyebrow: "Certification & registration",
    certificationTitle: "Recognised frameworks.",
    certificationAccent: "Buyer-ready evidence.",
    certificationIntro: "Registration and certification documents can be shared against the applicable product, facility, and shipment scope.",
    certifications: [
      { name: "FSSAI", type: "Food business registration", image: "/certifications/fssai.jpg" },
      { name: "APEDA", type: "Exporter registration", image: "/certifications/apeda.png" },
      { name: "HACCP", type: "Food safety system", image: "/certifications/haccp.png" },
      { name: "Spices Board India", type: "Exporter registration", image: "/certifications/spices-board.png" },
      { name: "Halal India", type: "Product certification", image: "/certifications/halal-india.png" },
      { name: "ISO 9001:2015", type: "Quality management", image: "/certifications/iso-9001.png" },
      { name: "Kosher", type: "Product certification", image: "/certifications/kosher.png" },
    ],
    certificationNote: "Demo compliance display: verify the certificate holder, product scope, registration number, and current validity before production publication.",
    closeTitle: "Have a market-specific standard?",
    closeCopy: "Share your specification sheet or approved sample. We’ll map the feasible product format, process controls, testing route, and inspection plan.",
    closeButton: "Discuss your requirement",
  },
  contact: {
    heroNumber: "05",
    heroKicker: "Export enquiry",
    heroTitle: "Let’s talk product,",
    heroAccent: "packing, and port.",
    heroIntro: "Share what you are sourcing. The more detail you provide, the more useful our first response can be.",
    asideEyebrow: "Direct trade desk",
    asideTitle: "Speak with a person,",
    asideAccent: "not a ticket.",
    asideCopy: "Our export team will review your product, packing, and destination details before replying.",
    emailLabel: "Email",
    phoneLabel: "Call / WhatsApp",
    addressLabel: "Export desk",
    responseValue: "< 1 day",
    responseLabel: "Typical response time",
    helpfulEyebrow: "Helpful details",
    helpfulTitle: "For a faster quotation, include:",
    helpfulItems: ["Product & format", "Required quantity", "Packing format", "Destination port", "Target timeline", "Inspection needs"],
  },
  form: {
    buyerStep: "01",
    buyerKicker: "Buyer details",
    buyerTitle: "Tell us who you are.",
    requiredNote: "* Required fields",
    nameLabel: "Your name *",
    namePlaceholder: "Full name",
    companyLabel: "Company *",
    companyPlaceholder: "Company name",
    countryLabel: "Country / market *",
    countryPlaceholder: "e.g. UAE",
    shipmentStep: "02",
    shipmentKicker: "Shipment requirement",
    shipmentTitle: "What should we quote?",
    productLabel: "Product *",
    productPlaceholder: "Select a product",
    mixedContainer: "Mixed container",
    quantityLabel: "Estimated quantity",
    quantityPlaceholder: "e.g. 1 × 20 ft container",
    destinationLabel: "Destination port",
    destinationPlaceholder: "e.g. Jebel Ali, Dubai",
    incotermLabel: "Preferred incoterm",
    incotermOptions: ["FOB", "CIF", "CNF", "Not sure yet"],
    messageLabel: "Tell us what you need",
    messagePlaceholder: "Format, packaging, destination port, timelines…",
    privacyNote: "Your details stay private and are only used for this quotation.",
    preparedNote: "Your enquiry is ready in your email app.",
    submitButton: "Prepare email enquiry",
    emailSubjectPrefix: "Export enquiry",
  },
};

export type SiteContent = typeof defaultSiteContent;
export type QualityStage = SiteContent["quality"]["stages"][number];
